#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/bloggen'
require 'getoptlong'

opts = GetoptLong.new(
  ['--help', '-h', GetoptLong::NO_ARGUMENT]
)

opts.each do |opt, _arg|
  case opt
  when '--help'
    puts <<~HELP
bloggen [OPTION] ... BLOGNAME SOURCE DEST

-h, --help:
  show help

BLOGNAME: The name of the blog to publish
SOURCE: Directory to load blog posts from
DEST: Directory to publish blog posts to
    HELP
    exit 0
  end
end

if ARGV.length != 3
  puts 'Invalid args (try --help)'
  exit 0
end

blogname = ARGV.shift
source = ARGV.shift
dest = ARGV.shift

bloggen = Bloggen.new(blogname, source, dest)
bloggen.generate
